juft_sonlar = list(range(120, 1200, 2))
print(juft_sonlar)
ygindi = sum(juft_sonlar)
print(ygindi)
print(max(juft_sonlar) - min(juft_sonlar))
print(len(juft_sonlar))
print(juft_sonlar[:20])
print(juft_sonlar[-20:])
print(juft_sonlar[520:550])
